### ISSUE TITLE
NeoPixel

### ISSUE THREAD

**Issue by maserowik** [SerBrynden/PiClock#16]
So I followed the instructions to connect the neopixel.jpb to the pi.  I have the strip feed via a 5 v 2.0 amp supply
https://github.com/SerBrynden/PiClock/blob/master/Documentation/NeoPixel.jpg

I then did 
cd PiClock
source venv/bin/activate
sudo apt install python3-dev
python3 -m pip install rpi_ws281x
deactivate
sudo reboot

So with the leds connected  what should happen?

Mike - N3BSQ

**Comment by maserowik** [comment]
When I issue this command  sudo /home/pi/PiClock/venv/bin/python3 /home/pi/PiClock/Leds/NeoAmbi.py  the led strips lights up.
not really sure what is to happen with the led and how they work.
Mike - N3BSQ

**Comment by SerBrynden** [comment]
No idea.  I don't use the LED strip.  It's a holdover from the original developer, n0bel, who implemented it to just add some ambient backlighting for the screen and make it look fancy.  I think you can edit NeoAmbi.py to change the color and brightness, but I don't have any way of testing it.

**Comment by maserowik** [comment]
I see in the instruction it says it need to be run as sudo.
