### ISSUE TITLE
Radar of Western Europe looks different to Rainviewer

### ISSUE THREAD

**Issue by feh123** [SerBrynden/PiClock#5]
It's not a major issue but it seems persistent and I thought I would mention it.

I have two radar maps - one at high zoom covering eastern England centred on Cambridge and a second map that covers England, Scotland, France, Denmark, western Germany and part of Switzerland.

The first map always duplicates rainviewer very accurately. They second map is great if displaying areas of high rainfall (green, yellow and red on PiClock) and they look accurate. Lower levels that the Rainviewer on my browser colour green are pale to dark blue and much larger on PiClock. They look like "blobs" rather than the well defined images on Rainviewer.

I have updated to the latest FW with git pull.

**Comment by SerBrynden** [comment]
RainViewer will look different in the web browser or on the mobile app.  The RainViewer API doesn't allow one to tweak the minimal precipitation intensity.  Also, the color scheme might be different.  You can change the radar color scheme in the PiClock config file and the schemes can be found here: https://www.rainviewer.com/api/color-schemes.html

**Comment by feh123** [comment]
Thanks for the info. It sounds like it could be about the minimal precipitation intensity.
In my Config.py file color is set to 6. There is 0 - 8 on the rainviewer link. Have you tried any others? I was thinking 8 maybe good as I recollect when I had Dark Sky working the european map looked okay. It was a long time ago however!

**Comment by SerBrynden** [comment]
I haven't really tried the other color schemes, but it's easy enough to change it in the config file and find one you like.

**Comment by feh123** [comment]
Yes - thanks for the info. I picked the original and although less colourful it makes the depiction of the rainfall on the two radar maps seem more aligned. I guess this maybe just my feeling! 


Sent from Yahoo Mail for iPad


On Tuesday, July 18, 2023, 5:07 pm, Brendan Curley ***@***.***> wrote:




I haven't really tried the other color schemes, but it's easy enough to change it in the config file and find one you like.
