### ISSUE TITLE
Rainviewer Radar Error

### ISSUE THREAD

**Issue by feh123** [SerBrynden/PiClock#6]
This morning my PiClock was not displaying rain radar and I do not see the rainviewer box at the top of my two radar maps. I checked the startup text and found:

radar1... get radar tiles for time 1689836400 (2023-07-20 08:00:00+01:00)
radar1 tile0 https://tilecache.rainviewer.com/v2/radar/1689836400//256/7/63/41/6/1_1.png
ERROR from rainviewer.com: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>404 - Map not found</title>
Radar2 shows the same error. Other than the radar the PiClock screen is showing all the usual data. Rainviewer does show the live map in my laptop browser so I don't think I have any connection issues at my end. Any thoughts on what is happening? Thanks.

**Comment by feh123** [comment]
Now two hours later the radar rainful pattern and the rainviewer.com logo have returned. Clearly some sort of issue at rainviewer or in the connection path. Glad to have the radar back!

**Comment by SerBrynden** [comment]
> Now two hours later the radar rainful pattern and the rainviewer.com logo have returned. Clearly some sort of issue at rainviewer or in the connection path. Glad to have the radar back!

It happens.  Did you try restarting PiClock?

**Comment by feh123** [comment]
Not yet. The radar just appeared - PiClock will reboot overnight so I will see what happens tomorrow.

    On Thursday, 20 July 2023 at 15:21:11 BST, Brendan Curley ***@***.***> wrote:  
 
 



Now two hours later the radar rainful pattern and the rainviewer.com logo have returned. Clearly some sort of issue at rainviewer or in the connection path. Glad to have the radar back!


It happens. Did you try restarting PiClock?

**Comment by SerBrynden** [comment]
Ok.  Just saying it might have resolved sooner if you restarted PiClock or rebooted the whole device right away.

**Comment by feh123** [comment]
Sorry I mis-understood your question. Yes I did try rebooting - it did not fix the radar.

    On Thursday, 20 July 2023 at 15:32:57 BST, Brendan Curley ***@***.***> wrote:  
 
 


Ok. Just saying it might have resolved sooner if you restarted PiClock or rebooted the whole device right away.
